### ISSUE TITLE
Sample Code Wont execute

### ISSUE THREAD

**Issue by pGit1** [neuralyzer/kerasvis#1]
from kerasvis import DBLogger

from keras.models import Sequential

from keras.layers import Dense

​

import scipy as sp

X = sp.rand(200, 20)

y = (sp.rand(200, 1) < .5).astype(int)

​

model = Sequential()

model.add(Dense(200, input_dim=20, activation="sigmoid"))

model.add(Dense(1, activation="sigmoid"))

model.compile("sgd", "binary_crossentropy")

​

logger = DBLogger(comment="An example run")

history = model.fit(X, y, nb_epoch=100, batch_size=64, verbose=0,

```
                validation_split=0.2, callbacks=[logger])
```

  File "/.../lib/python2.7/site-packages/kerasvis/callback.py", line 24
    def **init**(self, *, comment="No Comment", db_folder=None, id=None):
                        ^
SyntaxError: invalid syntax

**Comment by neuralyzer** [comment]
Hi,

the issues is Python 2.7 related. Kerasvis was developed for Python 3. Python 2 does not support keyword-only arguments  as introduced through PEP 3102 (https://www.python.org/dev/peps/pep-3102/). I used keyword only arguments in the initialization to not to run the risk to give arguments by position and thereby confuse the order. I think this could be changed at this place but I would have to check whether the current implementation is Python 2 incompatible at other places as well. Can you use Python 3?

**Comment by pGit1** [comment]
Ok makes sense. Py3 would break dependencies I have with other necessary
libraries.

**Comment by neuralyzer** [comment]
Interesting. Do you have custom legacy Python 2 code? All the major deep learning packages work well with Python 3 in my experience.
