### ISSUE TITLE
Error in dot syntax for adding layers

### ISSUE THREAD

**Issue by vijpandaturtle** [neuralyzer/kerasvis#7]
Hey there,
I am using keras to create a conv net and i keep getting an error in this statement 
 model.add(Activation('sigmoid'))
        ^
SyntaxError: invalid syntax

Any ideas on how to fix this ?

**Comment by neuralyzer** [comment]
Hi,

I'm not sure if I'm understanding how this is related to kerasvis. This is the repository of a web based visualization tool for keras runs. The main keras repository is this one here: https://github.com/fchollet/keras

Cheers!

**Comment by vijpandaturtle** [comment]
Sorry !! Realized that after I posted..anyway thanks :)
